### PR TITLE
- Update dependencies.

### PR DESCRIPTION
**Pull request by rehanone**
- Update documentation.
- Ability to provide RELAY_HOST_PASSWORD as docker secret.

### CODE REVIEW

**Comment by rehanone** [comment]
Once this PR is approved and merged, I would suggest tagging `v4.1.0` as this ups the Python version from `3.10` to `3.11`.

**Comment by rehanone** [comment]
@nguyenkims, can you please review this PR when you get the chance? Also I would like to volunteer to be one of the maintainers for this repo if that is okay and approved by you.

**Review by nguyenkims — APPROVED** [review]
LGTM!

**Comment by nguyenkims** [comment]
@rehanone thanks for creating the PR and offering help! I just added you the write access to the repo, let me know if that works.

**Comment by rehanone** [comment]
> @rehanone thanks for creating the PR and offering help! I just added you the write access to the repo, let me know if that works.

@nguyenkims Thank you!

**Pull request merged**
